# Generated by Django 6.0 on 2026-02-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('BEACH', 'Beach'), ('TEMPLE', 'Temple'), ('HILL_STATION', 'Hill Station'), ('HISTORICAL', 'Historical Place'), ('NATURE', 'Nature / Wildlife'), ('ADVENTURE', 'Adventure'), ('CITY', 'City / Urban'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image', models.ImageField(upload_to='explorer/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
