# Generated by Django 6.0 on 2026-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HillStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('description', models.TextField()),
                ('best_time_to_visit', models.CharField(help_text='e.g., April-June', max_length=200)),
                ('temperature_range', models.CharField(help_text='e.g., 10°C - 25°C', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='explorer/hill_stations/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hill Station',
                'verbose_name_plural': 'Hill Stations',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('BEACH', 'Beach'), ('HILL_STATION', 'Hill Station'), ('HISTORICAL', 'Historical Place'), ('NATURE', 'Nature / Wildlife'), ('ADVENTURE', 'Adventure'), ('CITY', 'City / Urban'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
