# Generated by Django 6.0 on 2026-02-24 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Day Plan',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('interest_category', models.CharField(choices=[('temples', 'Temples'), ('adventure', 'Adventure'), ('hill_stations', 'Hill Stations'), ('food', 'Food & Cuisine'), ('shopping', 'Shopping'), ('beaches', 'Beaches'), ('historical', 'Historical Places'), ('nature', 'Nature & Wildlife')], default='nature', max_length=20)),
                ('budget_tier', models.CharField(choices=[('economy', 'Economy (₹0 – ₹500/day)'), ('moderate', 'Moderate (₹500 – ₹2000/day)'), ('luxury', 'Luxury (₹2000+/day)')], default='moderate', max_length=10)),
                ('estimated_cost', models.PositiveIntegerField(default=0, help_text='Estimated cost per person in INR')),
                ('image', models.ImageField(blank=True, null=True, upload_to='itinerary/places/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL fallback', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tourist Place',
                'verbose_name_plural': 'Tourist Places',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='attraction',
        ),
        migrations.CreateModel(
            name='DayPlaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_items', to='itinerary.dayplan')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.touristplace')),
            ],
            options={
                'verbose_name': 'Day Place Item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('num_days', models.PositiveIntegerField(default=1)),
                ('budget', models.CharField(choices=[('economy', 'Economy (₹0 – ₹500/day)'), ('moderate', 'Moderate (₹500 – ₹2000/day)'), ('luxury', 'Luxury (₹2000+/day)')], default='moderate', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('interests', models.CharField(blank=True, help_text='Comma-separated list of interest values', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dayplan',
            name='travel_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='itinerary.travelplan'),
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='ItineraryItem',
        ),
    ]
