# Generated by Django 6.0 on 2026-02-26 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_dayplan_touristplace_remove_itineraryitem_itinerary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated hotel/accommodation cost in ₹', max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated transportation cost in ₹', max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated food & dining cost in ₹', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_estimate', to='itinerary.travelplan')),
            ],
            options={
                'verbose_name': 'Trip Budget',
                'verbose_name_plural': 'Trip Budgets',
            },
        ),
    ]
