# Generated by Django 6.0 on 2026-02-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANT', 'Restaurant'), ('TRANSPORT', 'Transport'), ('GUIDE', 'Local Guide')], max_length=20),
        ),
    ]
