# Generated by Django 6.0 on 2026-02-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='transport_category',
            field=models.CharField(blank=True, choices=[('CAB', 'Cabs / Taxis'), ('BUS', 'Buses'), ('TRAIN', 'Trains'), ('FLIGHT', 'Flights'), ('CAR_RENTAL', 'Car Rentals'), ('BIKE_RENTAL', 'Bike Rentals')], max_length=20, null=True),
        ),
    ]
