# Generated by Django 6.0.2 on 2026-02-24 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='City/State', max_length=200)),
                ('languages_known', models.CharField(help_text='Comma-separated languages', max_length=500)),
                ('experience_years', models.PositiveIntegerField(help_text='Years of experience')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='guides/profiles/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='guides/id_proofs/')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('specialization', models.CharField(blank=True, help_text='Areas of expertise', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_guide', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
