# Generated by Django 6.0.2 on 2026-02-25 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_localguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGuideUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('languages_known', models.CharField(max_length=500)),
                ('experience_years', models.PositiveIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='guides/profiles/')),
                ('specialization', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_update', to='bookings.localguide')),
            ],
        ),
    ]
