# Generated by Django 6.0 on 2026-02-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_localguideupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
