# Generated by Django 6.0 on 2026-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Primary guest name (optional)', max_length=200, null=True),
        ),
    ]
